### ISSUE TITLE
Comments of Rust-SDK

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wamr-rust-sdk#6]
- [ ] Runtime `impl` `Clone`, `Send` and `Sync`(for thread safe)
- [x] RuntimeError follows `std::error::Error` by `impl` `fmt()` of `fmt::Display`. ~~Plus `source` of `error::Error`~~. #7 
- [x] Allow set module name after loading. #12
- [x] Set more wasi args (in https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/include/wasm_export.h#L489 but not in rus) with more APIs or just do it once in all(wrap `wasm_runtime_set_wasi_args`). #9 
- [x] pass `runtime` to `module` and `instance` in order to keep its lifetime. #8

**Comment by Mossaka** [comment]
would be great to use the [`Builder` pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) to configure WASI context like args, envs, stdio, preopen file path and others.

**Comment by Mossaka** [comment]
Btw, does wamr support AOT precompile module? (e.g. [wasmtime's precompile](https://docs.wasmtime.dev/api/wasmtime/struct.Engine.html#method.precompile_module)) This is an useful feature in runwasi that we precompiles the module and caches it in containerd to reduce the total compilation time if the same module is being used many times.

**Comment by lum1n0us** [comment]
> does wamr support AOT precompile module? 
Yes. wamr supports AOT. Actually, we highly recommend to use AOT.

**Comment by lum1n0us** [comment]
@Mossaka since using a `Mutex` to protect a `static ref_cnt`(https://github.com/bytecodealliance/wamr-rust-sdk/blob/main/src/runtime.rs#L27), I guess *runtime* is already thread safe. So does it still need to `impl` `Send` and `Sync`?
